version: '3'
services:

  kamyarkalhorsite:
    image: kamyarkalhor.ir
    container_name: kamyarkalhor.ir
    volumes:
      - /var/www/main:/var/www/main
      - /var/www/blindxss:/var/www/blindxss
      - /var/www/blindssrf:/var/www/blindssrf
      - ./main.conf:/etc/apache2/sites-enabled/main.conf
      - ./Blind-xss.conf:/etc/apache2/sites-enabled/Blind-xss.conf
      - ./Blind-ssrf.conf:/etc/apache2/sites-enabled/Blind-ssrf.conf
    ports:
      - "80:80"
      - "443:443"