version: '3'
services:

  kamyarkalhorsite:
    image: kamyarkalhor.ir
    container_name: kamyarkalhor.ir
    volumes:
      - /var/www/html/main:/var/www/html/main
      - /var/www/html/blindxss:/var/www/html/blindxss
      - /var/www/html/blindssrf:/var/www/html/blindssrf
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=kamyarkalhor.ir
      - LETSENCRYPT_HOST=kamyarkalhor.ir