version: '3'
services:

  kamyarkalhorsite:
    image: kamyarkalhor.ir
    container_name: kamyarkalhor.ir
    volumes:
      - /var/www/main:/var/www/main
      - /var/www/blindxss:/var/www/blindxss
      - /var/www/blindssrf:/var/www/blindssrf
    ports:
      - "80:80"
      - "443:443"